### ISSUE TITLE
Dota client loses connection

### ISSUE THREAD

**Issue by Parapheen** [uleague/universityleague-match-stats#5]
Dota client can't fetch dota api. Seems that loosing connection and doesn't reconnect

**Comment by Parapheen** [comment]
After some examination and thinking process we discovered that it's not the connection causing the issue.

Most likely, it's the logic in `launching_machine`. Experimenting

**Comment by semenodp** [comment]
<img width="903" alt="Screen Shot 2020-11-06 at 8 10 15 AM" src="https://user-images.githubusercontent.com/39551930/98375319-944f0a80-2007-11eb-8e4d-4f07b828a9bd.png">

same issue again. please address ASAP

**Comment by Parapheen** [comment]
observing in #11
